### ISSUE TITLE
Pre-trained weights not accessible

### ISSUE THREAD

**Issue by pranavgundewar** [ZZYuting/GCN_ActionRecongtionTools#1]
Hi!

Thank you for sharing your work with us.

I am unable to access Baidu weights since I am in the US. Is it possible to share the weights over Google Drive or something similar?

Thank you again.

**Comment by ZZYuting** [comment]
for yolo
#!/bin/bash
# Download weights for vanilla YOLOv3
wget -c https://pjreddie.com/media/files/yolov3.weights
# # Download weights for tiny YOLOv3
wget -c https://pjreddie.com/media/files/yolov3-tiny.weights
# Download weights for backbone network
wget -c https://pjreddie.com/media/files/darknet53.conv.74
for hrnet model:
I will upload to google driver later, it's very slowe :)

**Comment by pranavgundewar** [comment]
Hi! Could you please grant access to the Google Drive model?
